# Site settings
title: VoodooBettie &mdash; Designer with a Heart of Code&trade;
email: contact@voodoobettie.com
description: > # this means to ignore newlines until "baseurl:"
  VoodooBettie is the designer with a heart of code. This is my website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.voodoobettie.com" # the base hostname & protocol for your site
twitter_username: voodoobettie
github_username:  voodoobettie
permalink: '/:title'

# Build settings
markdown: kramdown
