# Site settings
title: Voodoo Bettie;
email: contact@voodoobettie.com
description: > # this means to ignore newlines until "baseurl:"
  VoodooBettie &mdash; Designer with a Heart of Code&trade;
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://voodoobettie.githubpages.io" # the base hostname & protocol for your site
twitter_username: voodoobettie
github_username:  voodoobettie
permalink: '/:title'
excerpt_separator: <!--more-->
# gems: [jekyll-bootstrap, jekyll-font-awesome]
# sass: 
# 	sass-dir: _sass
collections: 
   portfolio:
     output: true 
     permalink: /portfolio/:path/
# Build settings
markdown: kramdown
